channels:
  - conda-forge
  - pypi
  - estnltk
  - pytorch
  - nvidia
dependencies:
  - python>=3.7
  - cudatoolkit>=11.0.0
  - librosa==0.9.2
  - tensorflow-gpu
  - nltk
  - estnltk=1.6.9b
  - pika
  - pytorch
  - torchvision
  - torchaudio
  - pyyaml>=6.0
  - pydantic==1.10.2
  - python-dotenv==0.21.0
  - ruamel.yaml==0.17.21
  - pip
  - pip:
      - phonemizer==2.2.1