name: deepvoice
channels:
  - anaconda
  - pytorch
  - estnltk
  - conda-forge
dependencies:
  - python==3.7.10
  - numpy=1.17.4
  - scipy==1.3.2
  - pytorch=1.8.1
  - Unidecode==1.1.1
  - inflect==4.0.0
  - librosa==0.7.1
  - numba==0.47.0
  - nltk==3.6.2
  - docopt==0.6.2
  - tensorboardx=1.2
  - estnltk=1.6.9b
  - pysoundfile==0.10.3.post1
  - pip
  - pip:
      - lws
      - nnmnkwii>=0.0.19
