name: deepvoice
channels:
  - anaconda
  - estnltk
  - conda-forge
  - defaults
dependencies:
  - python=3.6.4
  - numpy=1.17.4=py36hc1035e2_0
  - scipy==1.3.2
  - pytorch=1.3.1=cuda92py36hb0ba70e_0
  - Unidecode==1.1.1
  - inflect==4.0.0
  - librosa==0.7.1
  - numba==0.47.0
  - nltk==3.2.5
  - docopt==0.6.2
  - tensorboardx=1.2
  - estnltk=1.6.5beta=3.6
  - scikit-learn==0.22.1
  - flask=0.12.2
  - flask-cors=3.0.7
  - flask-restful=0.3.7
  - keras=2.2.4
  - pandas=0.23.4
  - pip
  - pip:
      - lws
      - nnmnkwii>=0.0.19
